#!/system/bin/sh
#
# handles zRam on startup
#

# handle zRam
PROP=`getprop persist.service.zram`
if [[ $PROP > 0 ]]; then
   SYSFS_PATH=/sys/block/zram0
   DEVPATH=/dev/zram0
   MEMTOTAL=$( awk '{ if ($1 eq "MemTotal:") print $2 ;exit }' </proc/meminfo )

   CCSIZE=$(($(($MEMTOTAL * $PROP)) / 100))
   /system/xbin/busybox mknod /dev/zram0 b 253 0
   echo 1 > $SYSFS_PATH/reset
   echo "$(($CCSIZE * 1024))" > $SYSFS_PATH/disksize
   /system/xbin/busybox mkswap $DEVPATH
   /system/xbin/busybox swapon $DEVPATH
fi

exit 0
