#!/system/bin/sh
##############################################
###        Simple zRam handler             ###
###      Copyright @ Munjeni 2012          ###
##############################################

# handle zRam
PROP=`getprop persist.service.zram`
if [[ $PROP > 0 ]]; then
	SYSFS_PATH=/sys/block/zram0
	DEVPATH=/dev/zram0
#	SWAPPINESS=`cat /proc/sys/vm/swappiness`
	MEMTOTAL=$( awk '{ if ($1 eq "MemTotal:") print $2 ;exit }' </proc/meminfo )

#	if [ ! "SWAPPINESS" = "30" ]; then
#		echo 30 > /proc/sys/vm/swappiness
#	fi

	CCSIZE=$(($(($MEMTOTAL * $PROP)) / 100))
	/system/xbin/toybox mknod /dev/zram0 b 253 0
	echo 1 > $SYSFS_PATH/reset
	echo "$(($CCSIZE * 1024))" > $SYSFS_PATH/disksize
	/system/xbin/toybox mkswap $DEVPATH
	/system/xbin/toybox swapon $DEVPATH
fi

exit 0
